### ISSUE TITLE
Support Telegram Alerts

### ISSUE THREAD

**Issue by joesixpack** [Neozaru/near-suricate#1]
Getting way too many alerts in my email inbox.  Let's support sending to Telegram.  It is a simple web API interface.

**Comment by Neozaru** [comment]
Hello @joesixpack.
First thanks for your feedback.

I just pushed code where you can use an existing owned bot to send you messages (same text as in emails), so you could remote `mail` from the `emitters` array and put a Telegram config instead.
I tested it very basically with creating a new bot using BotFather and using my own user ID as `channelId`. It does work in this context but I haven't tested it in other context. Also I didn't fully explore the Telegram API so I am not sure if the way I did it is the "correct" way.

**Comment by joesixpack** [comment]
I'm getting the below at startup when putting in telegram as an emitter:

```
Failed to process updates. { Error: 409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at buildConfig.then.then.then.then (/home/j/.nvm/versions/node/v10.16.3/lib/node_modules/near-suricate/node_modules/telegraf/core/network/client.js:281:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 409,
  response:
   { ok: false,
     error_code: 409,
     description:
      'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running' },
  description:
   'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',
  parameters: {},
  on:
   { method: 'getUpdates?offset=0&limit=100&timeout=30',
     payload: {} } }
```
